version: '3.3'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    network_mode: host
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      TZ: ${TZ}
